version: '3.8'

services:
  backend:
    build: ./services/backend
    volumes:
      - ./services/backend:/app
    command: uvicorn src.main:app --reload --host 0.0.0.0 --port 8000
    ports:
      - 8000:8000

  frontend:
    build: ./services/frontend
    volumes:
      - './services/frontend:/app'
      - '/app/node_modules'
    command: npm run dev
    ports:
      - 3000:3000